### ISSUE TITLE
Error in calling qp.drawImage

### ISSUE THREAD

**Issue by virusvfv** [skelsec/evilrdp#1]
Something strange error in Kali 2023.3
python 3.11
aadrwolf 0.2.7
PyQt5  5.15.10
PyQt5-Qt5 5.15.2
```
evilrdp -v rdp+ntlm-password://Administrator:Passw0rd@192.168.0.117

# evilrdp 0.0.1 
# Author: Tamas Jos @skelsec (info@skelsecprojects.com)

$ Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/evilrdp-0.0.1-py3.11.egg/evilrdp/gui.py", line 309, in updateImage
    qp.drawImage(event.x, event.y, event.image, 0, 0, event.width, event.height)
TypeError: arguments did not match any overloaded call:
  drawImage(self, r: QRectF, image: QImage): argument 1 has unexpected type 'int'
  drawImage(self, r: QRect, image: QImage): argument 1 has unexpected type 'int'
  drawImage(self, p: Union[QPointF, QPoint], image: QImage): argument 1 has unexpected type 'int'
  drawImage(self, p: QPoint, image: QImage): argument 1 has unexpected type 'int'
  drawImage(self, x: int, y: int, image: QImage, sx: int = 0, sy: int = 0, sw: int = -1, sh: int = -1, flags: Union[Qt.ImageConversionFlags, Qt.ImageConversionFlag] = Qt.ImageConversionFlag.AutoColor): argument 3 has unexpected type 'ImageQt'
```

**Comment by skelsec** [comment]
ahhh! thank you for reporting this.  
Issue being that with the introduction of pyqt6 the image rendering of aardwolf had to be changed (because qt6 api changed), and this change did not propagate to this library. will push out a new version soon that contains the update.

**Comment by skelsec** [comment]
fix pushed to main, please close the issue if it fixed your issue.

**Comment by virusvfv** [comment]
Hi skelsec !

Thanks for your quickly reply
Last commit DID NOT resolved problem. I see that you made commit  code as aardwolfgui. So It does not works in kali to ((

Recently I downloaded fresh kali distro: kali-2023.4 and replay this issue in "clean" kali system.
My steps were:
```
apt update

https://github.com/skelsec/evilrdp.git

cd evilrdp 

sudo python3 setup.py install

evilrdp rdp+ntlm-password://Administrator:Passw0rd@192.168.0.117 

# evilrdp 0.0.2 
# Author: Tamas Jos @skelsec (info@skelsecprojects.com)

$ Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/evilrdp-0.0.2-py3.11.egg/evilrdp/gui.py", line 312, in updateImage
    qp.drawImage(event.x, event.y, rect, 0, 0, event.width, event.height)
TypeError: arguments did not match any overloaded call:
  drawImage(self, r: QRectF, image: QImage): argument 1 has unexpected type 'int'
  drawImage(self, r: QRect, image: QImage): argument 1 has unexpected type 'int'
  drawImage(self, p: Union[QPointF, QPoint], image: QImage): argument 1 has unexpected type 'int'
  drawImage(self, p: QPoint, image: QImage): argument 1 has unexpected type 'int'
  drawImage(self, x: int, y: int, image: QImage, sx: int = 0, sy: int = 0, sw: int = -1, sh: int = -1, flags: Union[Qt.ImageConversionFlags, Qt.ImageConversionFlag] = Qt.ImageConversionFlag.AutoColor): argument 3 has unexpected type 'ImageQt'

python -V
    -> Python 3.11.6

pip3 list 
    -> aardwolf  0.2.8
```

Then I tried it with Ubuntu Desktop 22.04 with python 3.10 and it works well in this system !!
lib versions (aardwolf+pyqt5) were same  as in kali, only python differs.

So I am some confused about it ...
Due to that kali is default "evil" system for "evil"  guys I think that it's necessary  that evilrdp have to work with kali ))
Please help me to do this ))

**Comment by virusvfv** [comment]
Hello again !
After many iterations I found solution for kali-2023.4 (it works on kali-2023.3 and maybe others).
1. sudo apt remove python3-pyqt6
2. sudo pip3 install Pillow==9.5.0
3. profit )
p.s. with Pillow >= 10.0 does not works ...

And this is works with aardwolfgui too.
